[package]
name = "vitrine"
version = "0.1.28"
authors = ["Charly Lersteau"]
edition = "2021"
description = "A scriptable static site generator"
repository = "https://github.com/charlyisidore/vitrine"
license = "AGPL-3.0-only"
keywords = ["static", "site", "generator"]
categories = [
    "command-line-utilities",
    "parsing",
    "template-engine",
    "web-programming",
]

[workspace]
members = ["vitrine_derive"]

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.7", features = ["derive"] }
futures = "0.3.30"
globset = "0.4.14"
grass = "0.13.3"
katex = { version = "0.4.6", default-features = false, features = ["duktape"] }
lightningcss = "1.0.0-alpha.57"
lol_html = "1.2.1"
markdown-it = "0.6.0"
markdown-it-footnote = "0.2.0"
minify-html = "0.15.0"
minify-js = "0.5.6"
mlua = { version = "0.9.9", features = [
    "lua51",
    "send",
    "serialize",
    "vendored",
] }
notify-debouncer-full = { version = "0.3.1", default-features = false }
quick-xml = { version = "0.33.0", features = ["serialize"] }
quickjs_runtime = { version = "0.13.4", default-features = false, features = [
    "bellard",
] }
rhai = { version = "1.18.0", features = ["serde", "sync"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
serde_yaml = "0.9.34"
slug = "0.1.5"
swc_core = { version = "0.95.6", features = [
    "common",
    "ecma_codegen",
    "ecma_parser",
    "ecma_transforms_typescript",
    "ecma_visit",
] }
syntect = "5.2.0"
tera = "1.20.0"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
toml = "0.8.14"
tower-http = { version = "0.5.2", features = ["fs"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
vitrine_derive = { version = "=0.1.4", path = "vitrine_derive" }
walkdir = "2.5.0"

[dev-dependencies]
assert_cmd = "2.0.14"
assert_fs = "1.1.1"
predicates = "3.1.0"
