[package]
name = "vitrine"
version = "0.1.0"
authors = ["Charly Lersteau"]
edition = "2021"
description = "A simple static site generator"
license = "AGPL-3.0-only"
repository = "https://github.com/charlyisidore/vitrine"

[dependencies]
