[package]
name = "vitrine"
version = "0.1.14"
authors = ["Charly Lersteau"]
edition = "2021"
description = "A scriptable static site generator"
repository = "https://github.com/charlyisidore/vitrine"
license = "AGPL-3.0-only"
keywords = ["static", "site", "generator"]
categories = [
    "command-line-utilities",
    "parsing",
    "template-engine",
    "web-programming",
]

[workspace]
members = ["vitrine_derive"]

[dependencies]
anyhow = "1.0.75"
axum = "0.6.20"
clap = { version = "4.4.7", features = ["derive"] }
grass = "0.13.1"
katex = "0.4.6"
lightningcss = "1.0.0-alpha.50"
lol_html = "1.2.0"
markdown-it = "0.6.0"
markdown-it-footnote = "0.2.0"
minify-html = "0.11.1"
minify-js = "0.5.6"
mlua = { version = "0.9.1", features = ["lua51", "send", "serialize", "vendored"] }
notify-debouncer-full = { version = "0.3.1", default-features = false }
rhai = { version = "1.16.2", features = ["serde", "sync"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.107"
serde_yaml = "0.9.25"
slug = "0.1.4"
swc_core = { version = "0.87.10", features = [
    "__common",
    "__ecma",
    "__ecma_transforms",
    "__visit",
    "ecma_codegen",
    "ecma_parser",
    "ecma_transforms_typescript",
] }
syntect = "5.1.0"
tera = "1.19.1"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }
toml = "0.8.4"
tower-http = { version = "0.4.4", features = ["fs"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
vitrine_derive = { version = "=0.1.0", path = "vitrine_derive" }
walkdir = "2.4.0"

[dev-dependencies]
assert_cmd = "2.0.12"
assert_fs = "1.0.13"
predicates = "3.0.4"
