[package]
name = "vitrine"
version = "0.1.7"
authors = ["Charly Lersteau"]
edition = "2021"
description = "A scriptable static site generator"
repository = "https://github.com/charlyisidore/vitrine"
license = "AGPL-3.0-only"
keywords = ["static", "site", "generator"]
categories = [
    "command-line-utilities",
    "parsing",
    "template-engine",
    "web-programming",
]

[workspace]
members = ["vitrine_derive"]

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.7", features = ["derive"] }
grass = "0.13.1"
lightningcss = "1.0.0-alpha.50"
lol_html = "1.2.0"
markdown-it = "0.6.0"
minify-html = "0.11.1"
minify-js = "0.5.6"
mlua = { version = "0.9.1", features = ["lua51", "send", "serialize", "vendored"] }
rhai = { version = "1.16.2", features = ["serde", "sync"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.107"
serde_yaml = "0.9.25"
slug = "0.1.4"
syntect = "5.1.0"
tera = "1.19.1"
thiserror = "1.0.50"
toml = "0.8.4"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
vitrine_derive = { version = "=0.1.0", path = "vitrine_derive" }
walkdir = "2.4.0"
